import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    const val aapt2: String = "3.2.0-4818971" // available milestone: "3.3.0-alpha13-5013011" 

    const val appcompat: String = "1.0.0" // up-to-date

    const val com_android_tools_build_gradle: String =
            "3.2.0" // available milestone: "3.3.0-alpha13" 

    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "3.13.0" // available milestone: "3.15.0" 

    const val com_github_bumptech_glide_compiler: String = "4.8.0" // up-to-date

    const val constraintlayout: String = "2.0.0-alpha2" // up-to-date

    const val core_ktx: String = "1.0.0" // up-to-date

    const val core_testing: String = "2.0.0" // up-to-date

    const val databinding_adapters: String = "3.2.0" // available milestone: "3.3.0-alpha13" 

    const val databinding_common: String = "3.2.0" // available milestone: "3.3.0-alpha13" 

    const val databinding_compiler: String = "3.2.0" // available milestone: "3.3.0-alpha13" 

    const val databinding_runtime: String = "3.2.0" // available milestone: "3.3.0-alpha13" 

    const val espresso_contrib: String = "3.1.0-alpha4" // available milestone: "3.1.0-beta02" 

    const val espresso_core: String = "3.1.0-alpha4" // available milestone: "3.1.0-beta02" 

    const val espresso_intents: String = "3.1.0-alpha4" // available milestone: "3.1.0-beta02" 

    const val glide: String = "4.8.0" // up-to-date

    const val gson: String = "2.8.2" // available milestone: "2.8.5" 

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.4" // exceed the version found: 0.2.3

    const val junit: String = "4.12" // up-to-date

    const val kotlin_android_extensions: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_annotation_processing_gradle: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_gradle_plugin: String = "1.3.0-rc-146" // up-to-date

    const val kotlin_stdlib_jdk8: String = "1.3.0-rc-146" // up-to-date

    const val legacy_support_v4: String = "1.0.0" // up-to-date

    const val lifecycle_extensions: String = "2.0.0" // up-to-date

    const val lint_gradle: String = "26.2.0" // available milestone: "26.3.0-alpha13" 

    const val material: String = "1.0.0" // up-to-date

    const val navigation_fragment_ktx: String = "1.0.0-alpha06" // up-to-date

    const val navigation_safe_args_gradle_plugin: String = "1.0.0-alpha06" // up-to-date

    const val navigation_ui_ktx: String = "1.0.0-alpha06" // up-to-date

    const val recyclerview: String = "1.0.0" // up-to-date

    const val room_compiler: String = "2.0.0" // available milestone: "2.1.0-alpha01" 

    const val room_runtime: String = "2.0.0" // available milestone: "2.1.0-alpha01" 

    const val uiautomator: String = "2.2.0-alpha4" // available milestone: "2.2.0-beta02" 

    const val work_runtime_ktx: String = "1.0.0-alpha09" // available milestone: "1.0.0-alpha10" 

    /**
     *
     *   To update Gradle, edit the wrapper file at path:
     *      ./gradle/wrapper/gradle-wrapper.properties
     */
    object Gradle {
        const val runningVersion: String = "4.10"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181015235836+0000"

        const val releaseCandidate: String = ""
    }
}
